### ISSUE TITLE
TRACMASS v7.0 bug - Test Case error. 

### ISSUE THREAD

**Issue by oj-tooth** [TRACMASS/Tracmass#1]
**General information:**
platform: Mac OS
version: 7

**Problem description:**
I am looking to use TRACMASS in my Ph.D. research. Having cloned the latest version of TRACMASS (26/10/2020), the test case immediately returns an error on the first iteration - 'Wrong box horizontal (j - index)'. This error has similarly been experienced by my research supervisor.

- Below is the contents of the TRACMASS_err.csv:     
1,    150.07200,     99.50000,      0.50000,          1250.00000,      0.01000,  Wrong box horizontal (j - index)                                                                    

The previous version of TRACMASS committed on 12/10/2020 runs the test case without error.

Thanks in advance!!

**Comment by AitorAldama** [comment]
Thank you for raising the issue,

The update on **26/10/2020** introduced a bug in _mod_pos.F90_ on how to deal with the north folding. If _jperio_ was defined different from zero, TRACMASS was wrongly correcting trajectory positions even if they were outside the north fold region.

We fixed the bug in the latest committed version (**28/10/2020**). Do not hesitate to contact us if you find more problems.
