### ISSUE TITLE
Unable to evaluate tracers while using a subdomain.

### ISSUE THREAD

**Issue by oj-tooth** [TRACMASS/Tracmass#2]
Hi, 

I am currently attempting to use the latest version (18/12/2020) of TRACMASS with ORCA025 fields with dimensions (75 x 1021 x 1442) and a subdomain in the North Atlantic. Unfortunately, each time I enable tracers to be evaluated along trajectories I experience a Fortran runtime error in read_field.F90 - I have copied the output below for reference. I'm not sure whether this can be fixed directly in read_field.F90 (my previous attempts to modify line 179 directly crashed mod_loop.F90) and I would greatly appreciate some further advice on this issue. 

Thanks in advance, 

Ollie 

-------------------------------------------------------------------------------
 
 Model information:
 Project code  : ORCA025_Sim01
 Case name     : ORCA025_Sim01
 Namelist file : projects/ORCA025_Sim01/namelist_ORCA025_Sim01.in
 
 -------------------------------------------------------------------------------
 
 Configuration options:
  - Forward in time (nff = 1)
  - A subdomain has been choosen
      i index:   844 - 1122 
      j index:   673 - 856  
  - Three-dimensional trajectories (vertical fluxes computed)
  - Evaluate the value of these tracers along the trajectories:
     1- To (degC) 
     2- S (PSU) 
     3- sigma0 (kg/m3) 
 
 -------------------------------------------------------------------------------
 
At line 179 of file projects/ORCA025_Sim01/read_field.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'tracers' (1442/279)

**Comment by oj-tooth** [comment]
Following my question above:

Having explored this issue further, I believe the problem may arise as the tracer arrays are defined in init_tracer before the subdomain is defined in init_subdomain. The mismatch would then occur since imt and jmt are redefined once the tracers are already allocated to the global grid size (imt = 1442) rather than the subdomain (imt = 279).

**Comment by AitorAldama** [comment]
Thank you for raising the issue,

As you pointed out the tracers were initialised before the subdomain was defined. The order has been reversed in the latest commit (23/02/2021). Moreover, we have found more potential issues in the stream function calculation and in the initialisation of the trajectories if TRACMASS is initialised with a subdomain. 

 Do not hesitate to contact us if you find more problems.

**Comment by oj-tooth** [comment]
Thanks for making these changes so quickly!

Much appreciated, 

Ollie
